### PR TITLE
fix: muser is now upgraded to by default 

### LINKED ISSUE #28: Paid variant installs the free version
**Describe the bug**
The paid variant of the app seems to install the free version. 

**To Reproduce**
1. In the terminal, go to the root folder
2. Type `gradlew assemblePaidRelease`
3. If you're using the emulator, then drag and drop the `app/build/ouputs/piad/app-paid-release.apk` file. Or else,
 run the command `adb install app/build/ouputs/piad/app-paid-release.apk` after connecting your phone. 
4. Open the menu on the left and go the support. 
5. The app name is displayed as Muser 1.0.0 (Free)

**Expected behavior**
The paid variant should install the paid version that unlocks all features

**Observed behavior**
The paid variant installs the free version that asks the user to Upgrade

**Device and Android version:** 

Google Pixel 3 emulator. Android 10. Stock.  Google Play services version 20.04.14

### PR DESCRIPTION
**Pull request by BumbleFlash**
fixed the paid version bug. The app is now upgraded to paid by default.

"Closes #28"

### CODE REVIEW

File: app/src/main/java/com/simplecity/amp_library/ShuttleApplication.java [hunk 1]
```diff
@@ -93,11 +94,8 @@ public void onCreate() {
                 .create(this)
                 .inject(this);
 
-        if (LeakCanary.isInAnalyzerProcess(this)) {
-            // This process is dedicated to LeakCanary for heap analysis.
-            // You should not init your app in this process.
-            return;
-        }
+        ((ShuttleApplication) getApplicationContext()).setIsUpgraded(true);
```
Comment (barbeau) [inline app/src/main/java/com/simplecity/amp_library/ShuttleApplication.java]: Why is the LeakCanary code removed here?

I think a simpler/safer solution would be to do:

`private boolean isUpgraded = true;`

...in the class body, and then make `setIsUpgraded()` a no-op (you can just comment out the code there).

**Review by barbeau — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/simplecity/amp_library/ShuttleApplication.java (hunk 1 above)
Comment (BumbleFlash) [reply app/src/main/java/com/simplecity/amp_library/ShuttleApplication.java]: Ah! I might have highlighted the block by mistake. 
It definitely seems safer. Will do that.

**Review by barbeau — APPROVED** [review]

**Comment by barbeau** [comment]
Thanks @BumbleFlash! FYI, Whenever you've finished updating a PR with changes you can request a review again so I get pinged.
